module:
  hugoVersion:
    min: "0.84.0"

params:
  ananke_socials:
  - name: linkedin
    url: https://www.linkedin.com/in/giulioguarnone/
  - name: github
    url: https://github.com/julio77it    
  - name: instagram
    url: https://instagram.com/julio77it        